<a href="https://colab.research.google.com/github/shivi13102/Healthcare-Fraud-Provider-Detection-Analysis/blob/main/dataClean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm

In [38]:
# Load Beneficiary Data
train_beneficiary = pd.read_excel('/content/drive/My Drive/FDS PROJECT/Train_Beneficiarydata-1542865627584.xlsx')

In [ ]:
# Find the midpoint of the dataset
midpoint = len(train_beneficiary) // 2

# Split into two halves
train = train_beneficiary.iloc[:midpoint]
test = train_beneficiary.iloc[midpoint:]

# Display the two halves
display("Training data:\n", train)
display("Testing Data:\n", test)

'Training data:\n'

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,NaT,1,1,0,39,230,12,12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,NaT,2,1,0,39,280,12,12,...,2,2,2,2,2,2,0,0,30,50
2,BENE11003,1936-08-01,NaT,1,1,0,52,590,12,12,...,2,2,1,2,2,2,0,0,90,40
3,BENE11004,1922-07-01,NaT,1,1,0,39,270,12,12,...,2,1,1,1,1,2,0,0,1810,760
4,BENE11005,1935-09-01,NaT,1,1,0,24,680,12,12,...,2,1,2,2,2,2,0,0,1790,1200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69273,BENE85160,1945-05-01,NaT,1,1,0,10,510,12,12,...,1,1,2,1,1,2,0,0,1350,570
69274,BENE85161,1934-09-01,NaT,2,1,0,31,160,12,12,...,2,2,1,2,2,1,0,0,2760,200
69275,BENE85162,1943-12-01,NaT,2,1,0,26,680,12,12,...,2,1,1,2,2,2,0,0,240,610
69276,BENE85163,1942-03-01,NaT,1,1,0,10,570,12,12,...,2,1,1,2,2,2,0,0,1600,280
69277,BENE85164,1936-08-01,NaT,2,1,0,5,510,12,12,...,2,2,2,2,2,2,0,0,1740,320

'Testing Data:\n'

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
69278,BENE85165,1930-03-01,NaT,2,1,Y,50,360,12,12,...,2,1,1,2,2,2,0,0,1720,780
69279,BENE85166,1932-06-01,NaT,2,1,0,6,150,12,12,...,2,1,2,2,1,2,0,0,3140,500
69280,BENE85167,1927-10-01,NaT,1,1,0,10,70,12,12,...,2,2,1,2,2,2,0,0,1330,220
69281,BENE85168,1925-01-01,NaT,2,1,0,23,400,12,12,...,1,1,1,2,2,2,6000,1068,0,0
69282,BENE85169,1924-06-01,NaT,1,1,0,15,460,12,12,...,2,2,2,2,2,2,9300,3068,20,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138551,BENE159194,1939-07-01,NaT,1,1,0,39,140,12,12,...,2,2,2,2,2,2,0,0,430,460
138552,BENE159195,1938-12-01,NaT,2,1,0,49,530,12,12,...,2,1,2,2,2,2,0,0,880,100
138553,BENE159196,1916-06-01,NaT,2,1,0,6,150,12,12,...,1,1,1,2,2,2,2000,1068,3240,1390
138554,BENE159197,1930-01-01,NaT,1,1,0,16,560,12,12,...,2,2,1,2,2,2,0,0,2650,10
138555,BENE159198,1952-04-01,NaT,2,1,0,21,20,12,12,...,1,1,2,2,1,2,0,0,5470,1870

In [39]:
print(train.columns)
print(test.columns)

Index(['BeneID', 'DOB', 'DOD', 'Gender', 'Race', 'RenalDiseaseIndicator',
       'State', 'Country', 'NoOfMonths_PartACov', 'NoOfMonths_PartBCov',
       'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
       'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
       'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
       'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
       'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
       'ChronicCond_stroke', 'IPAnnualReimbursementAmt',
       'IPAnnualDeductibleAmt', 'OPAnnualReimbursementAmt',
       'OPAnnualDeductibleAmt'],
      dtype='object')
Index(['BeneID', 'DOB', 'DOD', 'Gender', 'Race', 'RenalDiseaseIndicator',
       'State', 'Country', 'NoOfMonths_PartACov', 'NoOfMonths_PartBCov',
       'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
       'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
       'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
       'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
       'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
       'ChronicCond_stroke', 'IPAnnualReimbursementAmt',
       'IPAnnualDeductibleAmt', 'OPAnnualReimbursementAmt',
       'OPAnnualDeductibleAmt'],
      dtype='object')

#Data cleaning process for Train beneficiary data

In [40]:
# Check for missing values
missing_values = train.isnull().sum()
print(missing_values)

BeneID                             0
DOB                                0
DOD                                0
Gender                             0
Race                               0
RenalDiseaseIndicator              0
State                              0
Country                            0
NoOfMonths_PartACov                0
NoOfMonths_PartBCov                0
ChronicCond_Alzheimer              0
ChronicCond_Heartfailure           0
ChronicCond_KidneyDisease          0
ChronicCond_Cancer                 0
ChronicCond_ObstrPulmonary         0
ChronicCond_Depression             0
ChronicCond_Diabetes               0
ChronicCond_IschemicHeart          0
ChronicCond_Osteoporasis           0
ChronicCond_rheumatoidarthritis    0
ChronicCond_stroke                 0
IPAnnualReimbursementAmt           0
IPAnnualDeductibleAmt              0
OPAnnualReimbursementAmt           0
OPAnnualDeductibleAmt              0
dtype: int64

In [41]:
# Replace null values in the 'DOD' column with "Alive"
train['DOD'].fillna("Alive", inplace=True)

# Display the updated DataFrame
display(train)

<ipython-input-41-001775b04a44>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train['DOD'].fillna("Alive", inplace=True)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,Country,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,Alive,M,1,N,39,230,12,12,...,1,1,1,0,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,Alive,F,1,N,39,280,12,12,...,0,0,0,0,0,0,0,0,30,50
2,BENE11003,1936-08-01,Alive,M,1,N,52,590,12,12,...,0,0,1,0,0,0,0,0,90,40
3,BENE11004,1922-07-01,Alive,M,1,N,39,270,12,12,...,0,1,1,1,1,0,0,0,1810,760
4,BENE11005,1935-09-01,Alive,M,1,N,24,680,12,12,...,0,1,0,0,0,0,0,0,1790,1200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69273,BENE85160,1945-05-01,Alive,M,1,N,10,510,12,12,...,1,1,0,1,1,0,0,0,1350,570
69274,BENE85161,1934-09-01,Alive,F,1,N,31,160,12,12,...,0,0,1,0,0,1,0,0,2760,200
69275,BENE85162,1943-12-01,Alive,F,1,N,26,680,12,12,...,0,1,1,0,0,0,0,0,240,610
69276,BENE85163,1942-03-01,Alive,M,1,N,10,570,12,12,...,0,1,1,0,0,0,0,0,1600,280
69277,BENE85164,1936-08-01,Alive,F,1,N,5,510,12,12,...,0,0,0,0,0,0,0,0,1740,320

In [42]:
# Display rows where 'DOD' does not contain "Alive"
non_alive_rows = train[train['DOD'] != "Alive"]

# Show the resulting DataFrame
display(non_alive_rows)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,Country,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
6,BENE11007,1940-09-01,2009-12-01 00:00:00,M,2,N,45,610,12,12,...,0,1,0,1,1,0,0,0,1490,160
206,BENE11217,1939-07-01,2009-09-01 00:00:00,M,3,Y,5,160,12,12,...,1,1,1,1,1,0,0,0,3880,650
207,BENE11218,1928-12-01,2009-09-01 00:00:00,M,1,N,14,141,12,12,...,1,1,1,1,0,1,19000,1068,110,50
219,BENE11231,1937-12-01,2009-05-01 00:00:00,F,2,N,45,810,12,12,...,0,1,1,1,0,0,4000,1068,300,30
525,BENE11558,1927-12-01,2009-12-01 00:00:00,F,1,N,14,141,12,12,...,0,0,1,0,0,0,0,0,50,80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68793,BENE84655,1920-12-01,2009-08-01 00:00:00,M,1,N,39,110,12,12,...,0,0,1,0,0,0,0,0,280,80
68798,BENE84660,1926-11-01,2009-10-01 00:00:00,F,2,N,5,200,12,12,...,1,1,1,0,0,0,13440,1068,680,20
68802,BENE84664,1928-10-01,2009-06-01 00:00:00,F,1,N,44,580,12,12,...,0,0,0,0,0,0,0,0,80,100
68830,BENE84693,1936-02-01,2009-09-01 00:00:00,F,1,N,45,720,12,12,...,0,1,1,0,1,0,0,0,190,440
69023,BENE84899,1941-10-01,2009-11-01 00:00:00,F,2,Y,49,870,12,12,...,1,1,0,0,1,1,0,0,190,60

In [43]:
# Check for duplicates in the 'BeneID' column of the train_beneficiary dataset
duplicates = train[train.duplicated(subset='BeneID')]

# Print the result
if not duplicates.empty:
    print(f"Found {len(duplicates)} duplicates in the 'BeneID' column of train_beneficiary.")
    print(duplicates)
else:
    print("No duplicates found in the 'BeneID' column of train_beneficiary.")

# Count the number of unique values in the 'BeneID' column of the train_beneficiary dataset
unique_beneid_count = train['BeneID'].nunique()

# Print the result
print(f"There are {unique_beneid_count} unique values in the 'BeneID' column of train_beneficiary.")

No duplicates found in the 'BeneID' column of train_beneficiary.
There are 67760 unique values in the 'BeneID' column of train_beneficiary.

In [44]:
# Rename the 'county' column to 'country'
train = train.rename(columns={'County': 'Country'})

# Verify the change
print(train.columns)

Index(['BeneID', 'DOB', 'DOD', 'Gender', 'Race', 'RenalDiseaseIndicator',
       'State', 'Country', 'NoOfMonths_PartACov', 'NoOfMonths_PartBCov',
       'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
       'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
       'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
       'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
       'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
       'ChronicCond_stroke', 'IPAnnualReimbursementAmt',
       'IPAnnualDeductibleAmt', 'OPAnnualReimbursementAmt',
       'OPAnnualDeductibleAmt'],
      dtype='object')

In [45]:
# List of columns that need to be converted
chronic_conditions = [
    'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
    'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
    'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
    'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
    'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
    'ChronicCond_stroke'
]

# Convert 2 to 0 and leave 1 as 1 for the specified columns
train[chronic_conditions] = train[chronic_conditions].replace({2: 0})

# Verify the changes
display(train[chronic_conditions].head())

,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke
0,1,0,1,0,0,1,1,1,0,1,1
1,0,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,1,0,0,0
3,1,1,0,0,0,0,1,1,1,1,0
4,0,0,0,0,1,0,1,0,0,0,0

In [47]:
# Replace 0 with 'N' in the RenalDiseaseIndicator column
train['RenalDiseaseIndicator'] = train['RenalDiseaseIndicator'].replace({0: 'N'})

#Verify the changes
print(train['RenalDiseaseIndicator'].value_counts())

RenalDiseaseIndicator
N    58257
Y     9503
Name: count, dtype: int64

In [48]:

# Replace 1 with 'M' and 2 with 'F' in the gender column for train_beneficiary
train['Gender'] = train['Gender'].replace({1: 'M', 2: 'F'})

# Verify the changes
print(train['Gender'].value_counts())

Gender
F    38565
M    29195
Name: count, dtype: int64

In [49]:
display(train)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,Country,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,Alive,M,1,N,39,230,12,12,...,1,1,1,0,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,Alive,F,1,N,39,280,12,12,...,0,0,0,0,0,0,0,0,30,50
2,BENE11003,1936-08-01,Alive,M,1,N,52,590,12,12,...,0,0,1,0,0,0,0,0,90,40
3,BENE11004,1922-07-01,Alive,M,1,N,39,270,12,12,...,0,1,1,1,1,0,0,0,1810,760
4,BENE11005,1935-09-01,Alive,M,1,N,24,680,12,12,...,0,1,0,0,0,0,0,0,1790,1200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69273,BENE85160,1945-05-01,Alive,M,1,N,10,510,12,12,...,1,1,0,1,1,0,0,0,1350,570
69274,BENE85161,1934-09-01,Alive,F,1,N,31,160,12,12,...,0,0,1,0,0,1,0,0,2760,200
69275,BENE85162,1943-12-01,Alive,F,1,N,26,680,12,12,...,0,1,1,0,0,0,0,0,240,610
69276,BENE85163,1942-03-01,Alive,M,1,N,10,570,12,12,...,0,1,1,0,0,0,0,0,1600,280
69277,BENE85164,1936-08-01,Alive,F,1,N,5,510,12,12,...,0,0,0,0,0,0,0,0,1740,320

In [50]:
# Remove rows where "Country" or "State" is 0
train = train[(train['Country'] != 0) & (train['State'] != 0)]

In [51]:
display(train)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,Country,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,Alive,M,1,N,39,230,12,12,...,1,1,1,0,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,Alive,F,1,N,39,280,12,12,...,0,0,0,0,0,0,0,0,30,50
2,BENE11003,1936-08-01,Alive,M,1,N,52,590,12,12,...,0,0,1,0,0,0,0,0,90,40
3,BENE11004,1922-07-01,Alive,M,1,N,39,270,12,12,...,0,1,1,1,1,0,0,0,1810,760
4,BENE11005,1935-09-01,Alive,M,1,N,24,680,12,12,...,0,1,0,0,0,0,0,0,1790,1200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69273,BENE85160,1945-05-01,Alive,M,1,N,10,510,12,12,...,1,1,0,1,1,0,0,0,1350,570
69274,BENE85161,1934-09-01,Alive,F,1,N,31,160,12,12,...,0,0,1,0,0,1,0,0,2760,200
69275,BENE85162,1943-12-01,Alive,F,1,N,26,680,12,12,...,0,1,1,0,0,0,0,0,240,610
69276,BENE85163,1942-03-01,Alive,M,1,N,10,570,12,12,...,0,1,1,0,0,0,0,0,1600,280
69277,BENE85164,1936-08-01,Alive,F,1,N,5,510,12,12,...,0,0,0,0,0,0,0,0,1740,320

In [53]:
# List of country codes to keep (195 countries)
country_codes_to_keep = [
    93, 355, 213, 376, 244, 1, 268, 54, 374, 61, 43, 994, 1, 242, 973, 880, 1, 246, 375, 32, 501, 229, 975,
    591, 387, 267, 55, 673, 359, 226, 257, 238, 855, 237, 236, 235, 56, 86, 57, 269, 242, 243, 506, 385, 53,
    357, 420, 45, 253, 1, 767, 1, 809, 1, 829, 1, 849, 593, 20, 503, 240, 291, 372, 268, 251, 679, 358, 33,
    241, 220, 995, 49, 233, 30, 1, 473, 502, 224, 245, 592, 509, 504, 36, 354, 91, 62, 98, 964, 353, 972, 39,
    1, 876, 81, 962, 7, 254, 686, 850, 82, 965, 996, 856, 371, 961, 266, 231, 218, 423, 370, 352, 261, 265,
    60, 960, 223, 356, 692, 222, 230, 52, 691, 373, 377, 976, 382, 212, 258, 95, 264, 674, 977, 31, 64, 505,
    227, 234, 389, 47, 968, 92, 680, 507, 675, 595, 51, 63, 48, 351, 974, 40, 7, 250, 1, 869, 1, 758, 1, 784,
    685, 378, 239, 966, 221, 381, 248, 232, 65, 421, 386, 677, 252, 27, 211, 34, 94, 249, 597, 46, 41, 963,
    886, 992, 255, 66, 670, 228, 676, 1, 868, 216, 90, 993, 688, 256, 380, 971, 44, 1, 598, 998, 678, 379,
    58, 84, 967, 260, 263
]

# Filter the DataFrame to keep only rows with specified country codes
filtered_df = train[train['Country'].isin(country_codes_to_keep)]

# Display the filtered DataFrame
display(filtered_df)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,Country,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,Alive,M,1,N,39,230,12,12,...,1,1,1,0,1,1,36000,3204,60,70
4,BENE11005,1935-09-01,Alive,M,1,N,24,680,12,12,...,0,1,0,0,0,0,0,0,1790,1200
8,BENE11009,1929-06-01,Alive,M,1,Y,44,230,12,12,...,0,1,0,0,0,0,0,0,100,0
9,BENE11010,1936-07-01,Alive,F,1,N,41,30,12,12,...,0,1,1,1,0,0,0,0,1170,660
20,BENE11021,1927-12-01,Alive,M,3,N,7,20,12,12,...,1,1,1,1,1,0,0,0,520,150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69263,BENE85150,1929-09-01,Alive,F,1,N,15,880,12,12,...,1,0,1,1,0,0,4000,1068,110,50
69266,BENE85153,1917-01-01,Alive,F,1,N,33,420,12,12,...,0,1,1,0,0,0,0,0,310,410
69271,BENE85158,1935-03-01,Alive,F,3,Y,31,370,12,12,...,0,0,1,1,0,0,5000,1068,20,0
69272,BENE85159,1919-10-01,Alive,F,2,N,51,230,12,12,...,0,0,1,0,0,0,0,0,3650,740
69275,BENE85162,1943-12-01,Alive,F,1,N,26,680,12,12,...,0,1,1,0,0,0,0,0,240,610

In [54]:
import os

# Define the path
file_path = '/content/drive/My Drive/Updated_Cleaned_Data/train_bene_cleaned_data.xlsx'

# Create the directory if it doesn't exist
os.makedirs(os.path.dirname(file_path), exist_ok=True)

# Save the DataFrame to the specified path
filtered_df.to_excel(file_path, index=False)

#Data cleaning process for Test beneficiary data

In [ ]:
# Check for missing values
missing_values = test.isnull().sum()
print(missing_values)

BeneID                                 0
DOB                                    0
DOD                                68587
Gender                                 0
Race                                   0
RenalDiseaseIndicator                  0
State                                  0
County                                 0
NoOfMonths_PartACov                    0
NoOfMonths_PartBCov                    0
ChronicCond_Alzheimer                  0
ChronicCond_Heartfailure               0
ChronicCond_KidneyDisease              0
ChronicCond_Cancer                     0
ChronicCond_ObstrPulmonary             0
ChronicCond_Depression                 0
ChronicCond_Diabetes                   0
ChronicCond_IschemicHeart              0
ChronicCond_Osteoporasis               0
ChronicCond_rheumatoidarthritis        0
ChronicCond_stroke                     0
IPAnnualReimbursementAmt               0
IPAnnualDeductibleAmt                  0
OPAnnualReimbursementAmt               0
OPAnnualDeductibleAmt                  0
dtype: int64

In [ ]:
# Replace null values in the 'DOD' column with "Alive"
test['DOD'].fillna("Alive", inplace=True)

# Display the updated DataFrame
display(test)

<ipython-input-22-a1acaeff1abe>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test['DOD'].fillna("Alive", inplace=True)
<ipython-input-22-a1acaeff1abe>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Alive' has dtype incompatible with datetime64[ns], please explicitly cast to a compatible dtype first.
  test['DOD'].fillna("Alive", inplace=True)
<ipython-input-22-a1acaeff1abe>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['DOD'].fillna("Alive", inplace=True)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
69278,BENE85165,1930-03-01,Alive,2,1,Y,50,360,12,12,...,2,1,1,2,2,2,0,0,1720,780
69279,BENE85166,1932-06-01,Alive,2,1,0,6,150,12,12,...,2,1,2,2,1,2,0,0,3140,500
69280,BENE85167,1927-10-01,Alive,1,1,0,10,70,12,12,...,2,2,1,2,2,2,0,0,1330,220
69281,BENE85168,1925-01-01,Alive,2,1,0,23,400,12,12,...,1,1,1,2,2,2,6000,1068,0,0
69282,BENE85169,1924-06-01,Alive,1,1,0,15,460,12,12,...,2,2,2,2,2,2,9300,3068,20,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138551,BENE159194,1939-07-01,Alive,1,1,0,39,140,12,12,...,2,2,2,2,2,2,0,0,430,460
138552,BENE159195,1938-12-01,Alive,2,1,0,49,530,12,12,...,2,1,2,2,2,2,0,0,880,100
138553,BENE159196,1916-06-01,Alive,2,1,0,6,150,12,12,...,1,1,1,2,2,2,2000,1068,3240,1390
138554,BENE159197,1930-01-01,Alive,1,1,0,16,560,12,12,...,2,2,1,2,2,2,0,0,2650,10
138555,BENE159198,1952-04-01,Alive,2,1,0,21,20,12,12,...,1,1,2,2,1,2,0,0,5470,1870

In [ ]:
# Display rows where 'DOD' does not contain "Alive"
non_alive_rows = test[test['DOD'] != "Alive"]

# Show the resulting DataFrame
display(non_alive_rows)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
69383,BENE85278,1935-04-01,2009-04-01 00:00:00,2,1,0,6,380,12,12,...,1,1,1,2,1,2,0,0,0,0
69415,BENE85314,1942-01-01,2009-05-01 00:00:00,1,1,0,44,780,0,12,...,2,1,1,2,1,2,0,0,500,20
69620,BENE85538,1940-04-01,2009-08-01 00:00:00,2,1,0,18,70,12,12,...,2,1,1,2,2,2,0,0,550,50
69650,BENE85568,1929-07-01,2009-11-01 00:00:00,2,1,0,10,400,12,12,...,2,1,2,2,2,2,0,0,20,0
69701,BENE85621,1938-08-01,2009-07-01 00:00:00,2,1,0,34,230,12,12,...,1,1,1,1,1,2,0,0,1250,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137494,BENE158067,1939-06-01,2009-08-01 00:00:00,2,1,0,10,400,12,12,...,2,1,1,1,2,2,7000,1068,1190,320
137497,BENE158070,1919-11-01,2009-06-01 00:00:00,2,1,0,33,420,12,12,...,1,1,1,2,2,2,0,0,40,0
137682,BENE158266,1929-07-01,2009-12-01 00:00:00,1,3,0,5,400,12,12,...,1,1,1,2,1,2,20200,1068,2220,250
137859,BENE158455,1932-08-01,2009-05-01 00:00:00,1,1,0,21,10,12,12,...,2,2,2,2,2,2,4000,1068,0,0
138061,BENE158676,1927-01-01,2009-07-01 00:00:00,1,1,0,23,810,12,12,...,2,1,1,2,2,2,0,0,70,100

In [ ]:
# Check for duplicates in the 'BeneID' column of the train_beneficiary dataset
duplicates = test[test.duplicated(subset='BeneID')]

# Print the result
if not duplicates.empty:
    print(f"Found {len(duplicates)} duplicates in the 'BeneID' column of test_beneficiary.")
    print(duplicates)
else:
    print("No duplicates found in the 'BeneID' column of test_beneficiary.")

# Count the number of unique values in the 'BeneID' column of the train_beneficiary dataset
unique_beneid_count = test['BeneID'].nunique()

# Print the result
print(f"There are {unique_beneid_count} unique values in the 'BeneID' column of test_beneficiary.")

No duplicates found in the 'BeneID' column of test_beneficiary.
There are 69278 unique values in the 'BeneID' column of test_beneficiary.

In [ ]:
# Rename the 'county' column to 'country'
test = test.rename(columns={'County': 'Country'})

# Verify the change
print(test.columns)

Index(['BeneID', 'DOB', 'DOD', 'Gender', 'Race', 'RenalDiseaseIndicator',
       'State', 'Country', 'NoOfMonths_PartACov', 'NoOfMonths_PartBCov',
       'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
       'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
       'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
       'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
       'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
       'ChronicCond_stroke', 'IPAnnualReimbursementAmt',
       'IPAnnualDeductibleAmt', 'OPAnnualReimbursementAmt',
       'OPAnnualDeductibleAmt'],
      dtype='object')

In [ ]:
# List of columns that need to be converted
chronic_conditions = [
    'ChronicCond_Alzheimer', 'ChronicCond_Heartfailure',
    'ChronicCond_KidneyDisease', 'ChronicCond_Cancer',
    'ChronicCond_ObstrPulmonary', 'ChronicCond_Depression',
    'ChronicCond_Diabetes', 'ChronicCond_IschemicHeart',
    'ChronicCond_Osteoporasis', 'ChronicCond_rheumatoidarthritis',
    'ChronicCond_stroke'
]

# Convert 2 to 0 and leave 1 as 1 for the specified columns
test[chronic_conditions] = test[chronic_conditions].replace({2: 0})

# Verify the changes
display(test[chronic_conditions].head())

,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke
69278,0,0,1,0,0,0,1,1,0,0,0
69279,1,0,0,0,0,0,1,0,0,1,0
69280,0,0,0,0,0,0,0,1,0,0,0
69281,1,1,0,1,1,1,1,1,0,0,0
69282,1,1,1,0,1,0,0,0,0,0,0

In [ ]:
# Replace 0 with 'N' in the RenalDiseaseIndicator column
test['RenalDiseaseIndicator'] = test['RenalDiseaseIndicator'].replace({0: 'N'})

#Verify the changes
print(test['RenalDiseaseIndicator'].value_counts())

RenalDiseaseIndicator
N    59398
Y     9880
Name: count, dtype: int64

In [ ]:
# Replace 1 with 'M' and 2 with 'F' in the gender column for train_beneficiary
test['Gender'] = test['Gender'].replace({1: 'M', 2: 'F'})

# Verify the changes
print(test['Gender'].value_counts())

Gender
F    39684
M    29594
Name: count, dtype: int64

In [ ]:
display(test)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,Country,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
69278,BENE85165,1930-03-01,Alive,F,1,Y,50,360,12,12,...,0,1,1,0,0,0,0,0,1720,780
69279,BENE85166,1932-06-01,Alive,F,1,N,6,150,12,12,...,0,1,0,0,1,0,0,0,3140,500
69280,BENE85167,1927-10-01,Alive,M,1,N,10,70,12,12,...,0,0,1,0,0,0,0,0,1330,220
69281,BENE85168,1925-01-01,Alive,F,1,N,23,400,12,12,...,1,1,1,0,0,0,6000,1068,0,0
69282,BENE85169,1924-06-01,Alive,M,1,N,15,460,12,12,...,0,0,0,0,0,0,9300,3068,20,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138551,BENE159194,1939-07-01,Alive,M,1,N,39,140,12,12,...,0,0,0,0,0,0,0,0,430,460
138552,BENE159195,1938-12-01,Alive,F,1,N,49,530,12,12,...,0,1,0,0,0,0,0,0,880,100
138553,BENE159196,1916-06-01,Alive,F,1,N,6,150,12,12,...,1,1,1,0,0,0,2000,1068,3240,1390
138554,BENE159197,1930-01-01,Alive,M,1,N,16,560,12,12,...,0,0,1,0,0,0,0,0,2650,10
138555,BENE159198,1952-04-01,Alive,F,1,N,21,20,12,12,...,1,1,0,0,1,0,0,0,5470,1870

In [ ]:
test = test.query('Country != 0 & State != 0')

In [ ]:
display(test)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,Country,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
69278,BENE85165,1930-03-01,Alive,F,1,Y,50,360,12,12,...,0,1,1,0,0,0,0,0,1720,780
69279,BENE85166,1932-06-01,Alive,F,1,N,6,150,12,12,...,0,1,0,0,1,0,0,0,3140,500
69280,BENE85167,1927-10-01,Alive,M,1,N,10,70,12,12,...,0,0,1,0,0,0,0,0,1330,220
69281,BENE85168,1925-01-01,Alive,F,1,N,23,400,12,12,...,1,1,1,0,0,0,6000,1068,0,0
69282,BENE85169,1924-06-01,Alive,M,1,N,15,460,12,12,...,0,0,0,0,0,0,9300,3068,20,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138551,BENE159194,1939-07-01,Alive,M,1,N,39,140,12,12,...,0,0,0,0,0,0,0,0,430,460
138552,BENE159195,1938-12-01,Alive,F,1,N,49,530,12,12,...,0,1,0,0,0,0,0,0,880,100
138553,BENE159196,1916-06-01,Alive,F,1,N,6,150,12,12,...,1,1,1,0,0,0,2000,1068,3240,1390
138554,BENE159197,1930-01-01,Alive,M,1,N,16,560,12,12,...,0,0,1,0,0,0,0,0,2650,10
138555,BENE159198,1952-04-01,Alive,F,1,N,21,20,12,12,...,1,1,0,0,1,0,0,0,5470,1870

In [ ]:
# List of country codes to keep (195 countries)
country_codes_to_keep = [
    93, 355, 213, 376, 244, 1, 268, 54, 374, 61, 43, 994, 1, 242, 973, 880, 1, 246, 375, 32, 501, 229, 975,
    591, 387, 267, 55, 673, 359, 226, 257, 238, 855, 237, 236, 235, 56, 86, 57, 269, 242, 243, 506, 385, 53,
    357, 420, 45, 253, 1, 767, 1, 809, 1, 829, 1, 849, 593, 20, 503, 240, 291, 372, 268, 251, 679, 358, 33,
    241, 220, 995, 49, 233, 30, 1, 473, 502, 224, 245, 592, 509, 504, 36, 354, 91, 62, 98, 964, 353, 972, 39,
    1, 876, 81, 962, 7, 254, 686, 850, 82, 965, 996, 856, 371, 961, 266, 231, 218, 423, 370, 352, 261, 265,
    60, 960, 223, 356, 692, 222, 230, 52, 691, 373, 377, 976, 382, 212, 258, 95, 264, 674, 977, 31, 64, 505,
    227, 234, 389, 47, 968, 92, 680, 507, 675, 595, 51, 63, 48, 351, 974, 40, 7, 250, 1, 869, 1, 758, 1, 784,
    685, 378, 239, 966, 221, 381, 248, 232, 65, 421, 386, 677, 252, 27, 211, 34, 94, 249, 597, 46, 41, 963,
    886, 992, 255, 66, 670, 228, 676, 1, 868, 216, 90, 993, 688, 256, 380, 971, 44, 1, 598, 998, 678, 379,
    58, 84, 967, 260, 263
]

# Filter the DataFrame to keep only rows with specified country codes
filtered_df = test[test['Country'].isin(country_codes_to_keep)]

# Display the filtered DataFrame
display(filtered_df)

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,Country,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
69284,BENE85171,1926-07-01,Alive,M,1,N,23,240,12,12,...,0,0,0,0,0,1,0,0,830,0
69285,BENE85172,1940-10-01,Alive,M,1,N,46,260,12,12,...,0,1,1,1,1,1,0,0,160,60
69290,BENE85177,1937-04-01,Alive,M,1,N,14,680,12,12,...,0,0,1,0,0,0,8000,1068,0,0
69291,BENE85178,1943-04-01,Alive,F,1,N,33,370,12,12,...,0,1,1,1,0,0,0,0,2060,320
69292,BENE85179,1932-03-01,Alive,F,1,N,22,90,12,12,...,0,0,0,0,0,0,0,0,40,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138542,BENE159184,1940-09-01,Alive,M,1,N,24,260,12,12,...,0,1,1,0,0,0,0,0,1110,230
138543,BENE159185,1935-06-01,Alive,F,1,N,5,90,12,12,...,0,1,0,0,0,0,0,0,70,200
138544,BENE159186,1930-01-01,Alive,F,1,N,5,370,12,12,...,0,1,0,1,0,0,0,0,1180,540
138550,BENE159192,1937-04-01,Alive,F,1,N,21,30,12,12,...,0,1,1,0,1,0,0,0,420,100
138555,BENE159198,1952-04-01,Alive,F,1,N,21,20,12,12,...,1,1,0,0,1,0,0,0,5470,1870

In [ ]:
# Define path for storing cleaned data
file_path = '/content/drive/My Drive/Updated_Cleaned_Data/test_bene_cleaned_data.xlsx'

# Save the DataFrame to the specified path
filtered_df.to_excel(file_path, index=False)